const AСTypes = {
    CREATE_USER: "CREATE_USER",
    ADD_QUESTION_IN_ARR: "ADD_QUESTION_IN_ARR",
    ANSWERED_QUESTION: "ANSWERED_QUESTION",
    POINTS_CHANGE: "POINTS_CHANGE",
    ID_CHANGE: "ID_CHANGE"
  };

export default AСTypes
